// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx_Vco7Z3tXD8gq48PzpoSd8bGdPZwOQU',
    appId: '1:898618419695:web:5dbcff50ba79e3a516ee1a',
    messagingSenderId: '898618419695',
    projectId: 'mpang-92fac',
    authDomain: 'mpang-92fac.firebaseapp.com',
    storageBucket: 'mpang-92fac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4TZ62OoNzob1ry6g5M4w-H0fQ2RFldn4',
    appId: '1:898618419695:android:de84e04831400fad16ee1a',
    messagingSenderId: '898618419695',
    projectId: 'mpang-92fac',
    storageBucket: 'mpang-92fac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB5DetHIdToohHpaPTqzdLNAp-1_gxtvo',
    appId: '1:898618419695:ios:01676ff8d53bb2d716ee1a',
    messagingSenderId: '898618419695',
    projectId: 'mpang-92fac',
    storageBucket: 'mpang-92fac.appspot.com',
    iosBundleId: 'com.example.mpangPhotoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB5DetHIdToohHpaPTqzdLNAp-1_gxtvo',
    appId: '1:898618419695:ios:01676ff8d53bb2d716ee1a',
    messagingSenderId: '898618419695',
    projectId: 'mpang-92fac',
    storageBucket: 'mpang-92fac.appspot.com',
    iosBundleId: 'com.example.mpangPhotoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx_Vco7Z3tXD8gq48PzpoSd8bGdPZwOQU',
    appId: '1:898618419695:web:3e1714de4cb24d0016ee1a',
    messagingSenderId: '898618419695',
    projectId: 'mpang-92fac',
    authDomain: 'mpang-92fac.firebaseapp.com',
    storageBucket: 'mpang-92fac.appspot.com',
  );

}